import { LegalLayout } from '../components/LegalLayout';

export function TermsPage() {
  return <LegalLayout eyebrow="Legal / Terms" title="Terms of Service" intro="These terms explain the rules for using FlakeCheck to inspect CI reliability, manage repository data, and operate automated test workflows.">
    <section><h2>1. Using FlakeCheck</h2><p>FlakeCheck is a software service for ingesting test reports, classifying failure behavior, calculating CI waste, and managing quarantine actions. You may use the service only for repositories, test reports, and credentials that you own or are authorized to process.</p></section>
    <section><h2>2. Accounts and access</h2><p>You are responsible for the accuracy of the account information you provide and for protecting access to your account. Passwordless codes are single-use and time-limited. Do not share sign-in codes, repository tokens, or OAuth credentials with another person.</p><p>Repository-scoped tokens must be used only for the repository they identify. You must promptly revoke a token if you believe it has been exposed.</p></section>
    <section><h2>3. Test data and repository content</h2><p>You retain ownership of the test reports, source references, failure messages, and other content you submit. You grant FlakeCheck the limited permission needed to store, normalize, classify, display, and export that content for your authorized workspace.</p><p>Do not submit secrets, credentials, or personal information that is not necessary for CI analysis. FlakeCheck applies sanitization to common credential patterns, but you remain responsible for the data sent to the service.</p></section>
    <section><h2>4. Classification results</h2><p>Classification, flake confidence, evidence, waste estimates, and quarantine recommendations are engineering aids. They are calculated from the data available to FlakeCheck and do not guarantee that a test will pass, that a regression will be detected, or that a deployment is safe.</p><p>You are responsible for reviewing evidence before changing CI behavior or quarantining a test.</p></section>
    <section><h2>5. Acceptable use</h2><p>You must not use FlakeCheck to bypass access controls, interfere with another workspace, probe systems without authorization, transmit malicious code, or overload the service. You must comply with applicable laws and the terms of any connected repository or CI provider.</p></section>
    <section><h2>6. Availability and changes</h2><p>We may improve, modify, or temporarily suspend parts of the service for maintenance, security, or operational reasons. We may update these terms when the service changes. The effective date above identifies the version shown on this page.</p></section>
    <section><h2>7. Account deletion</h2><p>You can request account deletion from the dashboard. Deletion removes personal account data, sessions, and linked OAuth accounts as described in the Privacy Policy. Repository data retention may also be subject to workspace or operational requirements.</p></section>
    <section><h2>8. Contact</h2><p>For questions about these terms or an authorized workspace, contact the FlakeCheck administrator for your organization.</p></section>
  </LegalLayout>;
}
